[project]
site_name = "REO amplifier"
site_url = "https://reo.biomedtech.space"
copyright = """\
Copyright &copy; 2024 - 2025 Space Biomed Technologies -
<a href="#__consent">Change cookie settings</a>
"""
nav = [
  { "Home" = "index.md" },
  { "Downloads" = "downloads.md" },
  { "Contact" = "contact.md" },
]

[project.extra.consent]
title = "Cookie consent"
description = """\
We use cookies to recognize your repeated visits and preferences, as well
as to measure the effectiveness of our documentation and whether users
find what they're searching for. With your consent, you're helping us to
make our documentation better.
"""

[[project.extra.social]]
icon = "fontawesome/brands/facebook"
link = "https://www.facebook.com/spacebiomedtech/"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/space-bmt"

[[project.extra.social]]
icon = "fontawesome/brands/instagram"
link = "https://www.instagram.com/spacebiomedtech/"

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.theme]
language = "en"
features = [
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.prune",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "search.suggest",
  "toc.follow",
  "toc.integrate",
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "blue"
accent = "orange"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "blue"
accent = "orange"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
